### ISSUE TITLE
Data set Accession Numbers not complete

### ISSUE THREAD

**Issue by nkarisan** [jessieren/DeepVirFinder#15]
It seems that in the supplementary file "SupplementaryTable1_NCBI_accession.xlsx", most of the records correspond to "pokaryote" are not given by their NCBI Accession id (possibly given by other type of ids), that would be good if they become available.

**Comment by jessieren** [comment]
Hi nkarisan,

Thanks for your message. The dataset contains various types of genomes. Some are complete genomes and some are assembled genomes. For example, for AATR01, it is the accession number of an assembled genome. The sequence dat a can be found here: https://www.ncbi.nlm.nih.gov/Traces/wgs/AATR01?display=proteins&page=1.

Jie

**Comment by nkarisan** [comment]
Thank you for your response, so that’s why my queries would fail. In that link example, the table consists of 4,507 proteins, did you mean that you have used all of them?
