### ISSUE TITLE
Stuck on loading models?

### ISSUE THREAD

**Issue by Joshcole2504** [jessieren/DeepVirFinder#30]
Hello,

I am having a problem with my run getting stuck on the first section, loading the models. 

I have downloaded the required dependancies and python is fully updated.

I input 

```
python dvf.py -i ~/Documents/PairwiseANI/my_seqs.fna -l 1000 -c 2
```

It returns 

```
Using Theano backend.
1. Loading Models.
   model directory /data2/joshcole/DeepVirFinder/models
Traceback (most recent call last):
  File "dvf.py", line 131, in <module>
    modDict[contigLengthk] = load_model(os.path.join(modDir, modName))
  File "/home/ggb_joshcole/miniconda3/envs/dvf/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/ggb_joshcole/miniconda3/envs/dvf/lib/python3.6/site-packages/keras/engine/saving.py", line 224, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

Any help with what I'm doing wrong would be greatly appreciated!

**Comment by Joshcole2504** [comment]
Apologies - Found the fix within the issues.

**Comment by Aciole-David** [comment]
> Apologies - Found the fix within the issues.

Hey @Joshcole2504, care to tell where did you find the fix? thanks!

**Comment by jessieren** [comment]
Please refer to this issue: https://github.com/jessieren/DeepVirFinder/issues/18

Basically, specify the version number of h5py in conda create:

`conda create --name dvf python=3.6 numpy theano=1.0.3 keras=2.2.4 scikit-learn Biopython h5py=2.10.0`
