### ISSUE TITLE
program uses more cores than specified

### ISSUE THREAD

**Issue by snayfach** [jessieren/DeepVirFinder#4]
I've noticed that by default DVF uses multiple cores (up to 20 on my machine) and that the flag `-c` or `--core` does not change this behavior. Do you know why this might be happening?

**Comment by bsiranosian** [comment]
This was really confusing to me as well, but disabling multiprocessing completely still used all my cpus. Which made me think the error was in Keras. Updating to keras 2.3 solved the problem for me. 

`conda install -c conda-forge keras=2.3`
